// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlqebvxmavrzousuqyjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1scWVidnhtYXZyem91c3VxeWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODMxNjgsImV4cCI6MjA4NjM1OTE2OH0.og7iVYNNM8fQVVIko8n0VxP-6mTd4faezgkOmdt_3rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});